-- ----------------------------
-- Records of countries
-- ----------------------------
INSERT INTO `tomos_countries` VALUES ('aw', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'AW', 'ABW', '297');
INSERT INTO `tomos_countries` VALUES ('af', 'Afghanistan', 'Islamic Republic of Afghanistan', 'افغانستان', 'جمهوری اسلامی افغانستان', 'AF', 'AFG', '93');
INSERT INTO `tomos_countries` VALUES ('ao', 'Angola', 'Republic of Angola', 'Angola', 'República de Angola', 'AO', 'AGO', '244');
INSERT INTO `tomos_countries` VALUES ('ai', 'Anguilla', 'Anguilla', 'Anguilla', 'Anguilla', 'AI', 'AIA', '1264');
INSERT INTO `tomos_countries` VALUES ('ax', 'Åland Islands', 'Åland Islands', 'Åland', 'Landskapet Åland', 'AX', 'ALA', '358');
INSERT INTO `tomos_countries` VALUES ('al', 'Albania', 'Republic of Albania', 'Shqipëria', 'Republika e Shqipërisë', 'AL', 'ALB', '355');
INSERT INTO `tomos_countries` VALUES ('ad', 'Andorra', 'Principality of Andorra', 'Andorra', 'Principat d\'Andorra', 'AD', 'AND', '376');
INSERT INTO `tomos_countries` VALUES ('ae', 'United Arab Emirates', 'United Arab Emirates', 'دولة الإمارات العربية المتحدة', 'الإمارات العربية المتحدة', 'AE', 'ARE', '971');
INSERT INTO `tomos_countries` VALUES ('ar', 'Argentina', 'Argentine Republic', 'Argentina', 'Argentine Republic', 'AR', 'ARG', '54');
INSERT INTO `tomos_countries` VALUES ('am', 'Armenia', 'Republic of Armenia', 'Հայաստան', 'Հայաստանի Հանրապետություն', 'AM', 'ARM', '374');
INSERT INTO `tomos_countries` VALUES ('as', 'American Samoa', 'American Samoa', 'American Samoa', 'American Samoa', 'AS', 'ASM', '1684');
INSERT INTO `tomos_countries` VALUES ('aq', 'Antarctica', 'Antarctica', 'Antarctica', 'Antarctica', 'AQ', 'ATA', null);
INSERT INTO `tomos_countries` VALUES ('tf', 'French Southern and Antarctic Lands', 'Territory of the French Southern and Antarctic Lands', 'Terres australes et antarctiques françaises', 'Territoire des Terres australes et antarctiques françaises', 'TF', 'ATF', null);
INSERT INTO `tomos_countries` VALUES ('ag', 'Antigua and Barbuda', 'Antigua and Barbuda', 'Antigua and Barbuda', 'Antigua and Barbuda', 'AG', 'ATG', '1268');
INSERT INTO `tomos_countries` VALUES ('au', 'Australia', 'Commonwealth of Australia', 'Australia', 'Commonwealth of Australia', 'AU', 'AUS', '61');
INSERT INTO `tomos_countries` VALUES ('at', 'Austria', 'Republic of Austria', 'Österreich', 'Republik Österreich', 'AT', 'AUT', '43');
INSERT INTO `tomos_countries` VALUES ('az', 'Azerbaijan', 'Republic of Azerbaijan', 'Azərbaycan', 'Azərbaycan Respublikası', 'AZ', 'AZE', '994');
INSERT INTO `tomos_countries` VALUES ('bi', 'Burundi', 'Republic of Burundi', 'Burundi', 'République du Burundi', 'BI', 'BDI', '257');
INSERT INTO `tomos_countries` VALUES ('be', 'Belgium', 'Kingdom of Belgium', 'Belgien', 'Königreich Belgien', 'BE', 'BEL', '32');
INSERT INTO `tomos_countries` VALUES ('bj', 'Benin', 'Republic of Benin', 'Bénin', 'République du Bénin', 'BJ', 'BEN', '229');
INSERT INTO `tomos_countries` VALUES ('bf', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'République du Burkina', 'BF', 'BFA', '226');
INSERT INTO `tomos_countries` VALUES ('bd', 'Bangladesh', 'People\'s Republic of Bangladesh', 'বাংলাদেশ', 'বাংলাদেশ গণপ্রজাতন্ত্রী', 'BD', 'BGD', '880');
INSERT INTO `tomos_countries` VALUES ('bg', 'Bulgaria', 'Republic of Bulgaria', 'България', 'Република България', 'BG', 'BGR', '359');
INSERT INTO `tomos_countries` VALUES ('bh', 'Bahrain', 'Kingdom of Bahrain', '‏البحرين', 'مملكة البحرين', 'BH', 'BHR', '973');
INSERT INTO `tomos_countries` VALUES ('bs', 'Bahamas', 'Commonwealth of the Bahamas', 'Bahamas', 'Commonwealth of the Bahamas', 'BS', 'BHS', '1242');
INSERT INTO `tomos_countries` VALUES ('ba', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'Bosna i Hercegovina', 'Bosna i Hercegovina', 'BA', 'BIH', '387');
INSERT INTO `tomos_countries` VALUES ('bl', 'Saint Barthélemy', 'Collectivity of Saint Barthélemy', 'Saint-Barthélemy', 'Collectivité de Saint-Barthélemy', 'BL', 'BLM', '590');
INSERT INTO `tomos_countries` VALUES ('by', 'Belarus', 'Republic of Belarus', 'Белару́сь', 'Рэспубліка Беларусь', 'BY', 'BLR', '375');
INSERT INTO `tomos_countries` VALUES ('bz', 'Belize', 'Belize', 'Belize', 'Belize', 'BZ', 'BLZ', '501');
INSERT INTO `tomos_countries` VALUES ('bm', 'Bermuda', 'Bermuda', 'Bermuda', 'Bermuda', 'BM', 'BMU', '1441');
INSERT INTO `tomos_countries` VALUES ('bo', 'Bolivia', 'Plurinational State of Bolivia', 'Wuliwya', 'Wuliwya Suyu', 'BO', 'BOL', '591');
INSERT INTO `tomos_countries` VALUES ('br', 'Brazil', 'Federative Republic of Brazil', 'Brasil', 'República Federativa do Brasil', 'BR', 'BRA', '55');
INSERT INTO `tomos_countries` VALUES ('bb', 'Barbados', 'Barbados', 'Barbados', 'Barbados', 'BB', 'BRB', '1246');
INSERT INTO `tomos_countries` VALUES ('bn', 'Brunei', 'Nation of Brunei, Abode of Peace', 'Negara Brunei Darussalam', 'Nation of Brunei, Abode Damai', 'BN', 'BRN', '673');
INSERT INTO `tomos_countries` VALUES ('bt', 'Bhutan', 'Kingdom of Bhutan', 'འབྲུག་ཡུལ་', 'འབྲུག་རྒྱལ་ཁབ་', 'BT', 'BTN', '975');
INSERT INTO `tomos_countries` VALUES ('bv', 'Bouvet Island', 'Bouvet Island', 'Bouvetøya', 'Bouvetøya', 'BV', 'BVT', null);
INSERT INTO `tomos_countries` VALUES ('bw', 'Botswana', 'Republic of Botswana', 'Botswana', 'Republic of Botswana', 'BW', 'BWA', '267');
INSERT INTO `tomos_countries` VALUES ('cf', 'Central African Republic', 'Central African Republic', 'République centrafricaine', 'République centrafricaine', 'CF', 'CAF', '236');
INSERT INTO `tomos_countries` VALUES ('ca', 'Canada', 'Canada', 'Canada', 'Canada', 'CA', 'CAN', '1');
INSERT INTO `tomos_countries` VALUES ('cc', 'Cocos (Keeling) Islands', 'Territory of the Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'Territory of the Cocos (Keeling) Islands', 'CC', 'CCK', '61');
INSERT INTO `tomos_countries` VALUES ('ch', 'Switzerland', 'Swiss Confederation', 'Suisse', 'Confédération suisse', 'CH', 'CHE', '41');
INSERT INTO `tomos_countries` VALUES ('cl', 'Chile', 'Republic of Chile', 'Chile', 'República de Chile', 'CL', 'CHL', '56');
INSERT INTO `tomos_countries` VALUES ('cn', 'China', 'People\'s Republic of China', '中国', '中华人民共和国', 'CN', 'CHN', '86');
INSERT INTO `tomos_countries` VALUES ('ci', 'Ivory Coast', 'Republic of Côte d\'Ivoire', 'Côte d\'Ivoire', 'République de Côte d\'Ivoire', 'CI', 'CIV', '225');
INSERT INTO `tomos_countries` VALUES ('cm', 'Cameroon', 'Republic of Cameroon', 'Cameroon', 'Republic of Cameroon', 'CM', 'CMR', '237');
INSERT INTO `tomos_countries` VALUES ('cd', 'DR Congo', 'Democratic Republic of the Congo', 'RD Congo', 'République démocratique du Congo', 'CD', 'COD', '243');
INSERT INTO `tomos_countries` VALUES ('cg', 'Republic of the Congo', 'Republic of the Congo', 'République du Congo', 'République du Congo', 'CG', 'COG', '242');
INSERT INTO `tomos_countries` VALUES ('ck', 'Cook Islands', 'Cook Islands', 'Cook Islands', 'Cook Islands', 'CK', 'COK', '682');
INSERT INTO `tomos_countries` VALUES ('co', 'Colombia', 'Republic of Colombia', 'Colombia', 'República de Colombia', 'CO', 'COL', '57');
INSERT INTO `tomos_countries` VALUES ('km', 'Comoros', 'Union of the Comoros', 'القمر‎', 'الاتحاد القمري', 'KM', 'COM', '269');
INSERT INTO `tomos_countries` VALUES ('cv', 'Cape Verde', 'Republic of Cabo Verde', 'Cabo Verde', 'República de Cabo Verde', 'CV', 'CPV', '238');
INSERT INTO `tomos_countries` VALUES ('cr', 'Costa Rica', 'Republic of Costa Rica', 'Costa Rica', 'República de Costa Rica', 'CR', 'CRI', '506');
INSERT INTO `tomos_countries` VALUES ('cu', 'Cuba', 'Republic of Cuba', 'Cuba', 'República de Cuba', 'CU', 'CUB', '53');
INSERT INTO `tomos_countries` VALUES ('cw', 'Curaçao', 'Country of Curaçao', 'Curaçao', 'Country of Curaçao', 'CW', 'CUW', '599');
INSERT INTO `tomos_countries` VALUES ('cx', 'Christmas Island', 'Territory of Christmas Island', 'Christmas Island', 'Territory of Christmas Island', 'CX', 'CXR', '61');
INSERT INTO `tomos_countries` VALUES ('ky', 'Cayman Islands', 'Cayman Islands', 'Cayman Islands', 'Cayman Islands', 'KY', 'CYM', '1345');
INSERT INTO `tomos_countries` VALUES ('cy', 'Cyprus', 'Republic of Cyprus', 'Κύπρος', 'Δημοκρατία της Κύπρος', 'CY', 'CYP', '357');
INSERT INTO `tomos_countries` VALUES ('cz', 'Czech Republic', 'Czech Republic', 'Česká republika', 'česká republika', 'CZ', 'CZE', '420');
INSERT INTO `tomos_countries` VALUES ('de', 'Germany', 'Federal Republic of Germany', 'Deutschland', 'Bundesrepublik Deutschland', 'DE', 'DEU', '49');
INSERT INTO `tomos_countries` VALUES ('dj', 'Djibouti', 'Republic of Djibouti', 'جيبوتي‎', 'جمهورية جيبوتي', 'DJ', 'DJI', '253');
INSERT INTO `tomos_countries` VALUES ('dm', 'Dominica', 'Commonwealth of Dominica', 'Dominica', 'Commonwealth of Dominica', 'DM', 'DMA', '1767');
INSERT INTO `tomos_countries` VALUES ('dk', 'Denmark', 'Kingdom of Denmark', 'Danmark', 'Kongeriget Danmark', 'DK', 'DNK', '45');
INSERT INTO `tomos_countries` VALUES ('do', 'Dominican Republic', 'Dominican Republic', 'República Dominicana', 'República Dominicana', 'DO', 'DOM', '1809');
INSERT INTO `tomos_countries` VALUES ('dz', 'Algeria', 'People\'s Democratic Republic of Algeria', 'الجزائر', 'الجمهورية الديمقراطية الشعبية الجزائرية', 'DZ', 'DZA', '213');
INSERT INTO `tomos_countries` VALUES ('ec', 'Ecuador', 'Republic of Ecuador', 'Ecuador', 'República del Ecuador', 'EC', 'ECU', '593');
INSERT INTO `tomos_countries` VALUES ('eg', 'Egypt', 'Arab Republic of Egypt', 'مصر', 'جمهورية مصر العربية', 'EG', 'EGY', '20');
INSERT INTO `tomos_countries` VALUES ('er', 'Eritrea', 'State of Eritrea', 'إرتريا‎', 'دولة إرتريا', 'ER', 'ERI', '291');
INSERT INTO `tomos_countries` VALUES ('eh', 'Western Sahara', 'Sahrawi Arab Democratic Republic', 'Western Sahara', 'Sahrawi Arab Democratic Republic', 'EH', 'ESH', '212');
INSERT INTO `tomos_countries` VALUES ('es', 'Spain', 'Kingdom of Spain', 'Espanya', 'Regne d\'Espanya', 'ES', 'ESP', '34');
INSERT INTO `tomos_countries` VALUES ('ee', 'Estonia', 'Republic of Estonia', 'Eesti', 'Eesti Vabariik', 'EE', 'EST', '372');
INSERT INTO `tomos_countries` VALUES ('et', 'Ethiopia', 'Federal Democratic Republic of Ethiopia', 'ኢትዮጵያ', 'የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ', 'ET', 'ETH', '251');
INSERT INTO `tomos_countries` VALUES ('fi', 'Finland', 'Republic of Finland', 'Suomi', 'Suomen tasavalta', 'FI', 'FIN', '358');
INSERT INTO `tomos_countries` VALUES ('fj', 'Fiji', 'Republic of Fiji', 'Fiji', 'Republic of Fiji', 'FJ', 'FJI', '679');
INSERT INTO `tomos_countries` VALUES ('fk', 'Falkland Islands', 'Falkland Islands', 'Falkland Islands', 'Falkland Islands', 'FK', 'FLK', '500');
INSERT INTO `tomos_countries` VALUES ('fr', 'France', 'French Republic', 'France', 'République française', 'FR', 'FRA', '33');
INSERT INTO `tomos_countries` VALUES ('fo', 'Faroe Islands', 'Faroe Islands', 'Færøerne', 'Færøerne', 'FO', 'FRO', '298');
INSERT INTO `tomos_countries` VALUES ('fm', 'Micronesia', 'Federated States of Micronesia', 'Micronesia', 'Federated States of Micronesia', 'FM', 'FSM', '691');
INSERT INTO `tomos_countries` VALUES ('ga', 'Gabon', 'Gabonese Republic', 'Gabon', 'République gabonaise', 'GA', 'GAB', '241');
INSERT INTO `tomos_countries` VALUES ('gb', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'GB', 'GBR', '44');
INSERT INTO `tomos_countries` VALUES ('ge', 'Georgia', 'Georgia', 'საქართველო', 'საქართველო', 'GE', 'GEO', '995');
INSERT INTO `tomos_countries` VALUES ('gg', 'Guernsey', 'Bailiwick of Guernsey', 'Guernsey', 'Bailiwick of Guernsey', 'GG', 'GGY', '44');
INSERT INTO `tomos_countries` VALUES ('gh', 'Ghana', 'Republic of Ghana', 'Ghana', 'Republic of Ghana', 'GH', 'GHA', '233');
INSERT INTO `tomos_countries` VALUES ('gi', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'GI', 'GIB', '350');
INSERT INTO `tomos_countries` VALUES ('gn', 'Guinea', 'Republic of Guinea', 'Guinée', 'République de Guinée', 'GN', 'GIN', '224');
INSERT INTO `tomos_countries` VALUES ('gp', 'Guadeloupe', 'Guadeloupe', 'Guadeloupe', 'Guadeloupe', 'GP', 'GLP', '590');
INSERT INTO `tomos_countries` VALUES ('gm', 'Gambia', 'Republic of the Gambia', 'Gambia', 'Republic of the Gambia', 'GM', 'GMB', '220');
INSERT INTO `tomos_countries` VALUES ('gw', 'Guinea-Bissau', 'Republic of Guinea-Bissau', 'Guiné-Bissau', 'República da Guiné-Bissau', 'GW', 'GNB', '245');
INSERT INTO `tomos_countries` VALUES ('gq', 'Equatorial Guinea', 'Republic of Equatorial Guinea', 'Guinée équatoriale', 'République de la Guinée Équatoriale', 'GQ', 'GNQ', '240');
INSERT INTO `tomos_countries` VALUES ('gr', 'Greece', 'Hellenic Republic', 'Ελλάδα', 'Ελληνική Δημοκρατία', 'GR', 'GRC', '30');
INSERT INTO `tomos_countries` VALUES ('gd', 'Grenada', 'Grenada', 'Grenada', 'Grenada', 'GD', 'GRD', '1473');
INSERT INTO `tomos_countries` VALUES ('gl', 'Greenland', 'Greenland', 'Kalaallit Nunaat', 'Kalaallit Nunaat', 'GL', 'GRL', '299');
INSERT INTO `tomos_countries` VALUES ('gt', 'Guatemala', 'Republic of Guatemala', 'Guatemala', 'República de Guatemala', 'GT', 'GTM', '502');
INSERT INTO `tomos_countries` VALUES ('gf', 'French Guiana', 'Guiana', 'Guyane française', 'Guyanes', 'GF', 'GUF', '594');
INSERT INTO `tomos_countries` VALUES ('gu', 'Guam', 'Guam', 'Guåhån', 'Guåhån', 'GU', 'GUM', '1671');
INSERT INTO `tomos_countries` VALUES ('gy', 'Guyana', 'Co-operative Republic of Guyana', 'Guyana', 'Co-operative Republic of Guyana', 'GY', 'GUY', '592');
INSERT INTO `tomos_countries` VALUES ('hk', 'Hong Kong', 'Hong Kong Special Administrative Region of the People\'s Republic of China', 'Hong Kong', 'Hong Kong Special Administrative Region of the People\'s Republic of China', 'HK', 'HKG', '852');
INSERT INTO `tomos_countries` VALUES ('hm', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'HM', 'HMD', null);
INSERT INTO `tomos_countries` VALUES ('hn', 'Honduras', 'Republic of Honduras', 'Honduras', 'República de Honduras', 'HN', 'HND', '504');
INSERT INTO `tomos_countries` VALUES ('hr', 'Croatia', 'Republic of Croatia', 'Hrvatska', 'Republika Hrvatska', 'HR', 'HRV', '385');
INSERT INTO `tomos_countries` VALUES ('ht', 'Haiti', 'Republic of Haiti', 'Haïti', 'République d\'Haïti', 'HT', 'HTI', '509');
INSERT INTO `tomos_countries` VALUES ('hu', 'Hungary', 'Hungary', 'Magyarország', 'Magyarország', 'HU', 'HUN', '36');
INSERT INTO `tomos_countries` VALUES ('id', 'Indonesia', 'Republic of Indonesia', 'Indonesia', 'Republik Indonesia', 'ID', 'IDN', '62');
INSERT INTO `tomos_countries` VALUES ('im', 'Isle of Man', 'Isle of Man', 'Isle of Man', 'Isle of Man', 'IM', 'IMN', '44');
INSERT INTO `tomos_countries` VALUES ('in', 'India', 'Republic of India', 'India', 'Republic of India', 'IN', 'IND', '91');
INSERT INTO `tomos_countries` VALUES ('io', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'British Indian Ocean Territory', 'IO', 'IOT', '246');
INSERT INTO `tomos_countries` VALUES ('ie', 'Ireland', 'Republic of Ireland', 'Ireland', 'Republic of Ireland', 'IE', 'IRL', '353');
INSERT INTO `tomos_countries` VALUES ('ir', 'Iran', 'Islamic Republic of Iran', 'ایران', 'جمهوری اسلامی ایران', 'IR', 'IRN', '98');
INSERT INTO `tomos_countries` VALUES ('iq', 'Iraq', 'Republic of Iraq', 'العراق', 'جمهورية العراق', 'IQ', 'IRQ', '964');
INSERT INTO `tomos_countries` VALUES ('is', 'Iceland', 'Iceland', 'Ísland', 'Ísland', 'IS', 'ISL', '354');
INSERT INTO `tomos_countries` VALUES ('il', 'Israel', 'State of Israel', 'إسرائيل', 'دولة إسرائيل', 'IL', 'ISR', '972');
INSERT INTO `tomos_countries` VALUES ('it', 'Italy', 'Italian Republic', 'Italien', 'Italienische Republik', 'IT', 'ITA', '39');
INSERT INTO `tomos_countries` VALUES ('jm', 'Jamaica', 'Jamaica', 'Jamaica', 'Jamaica', 'JM', 'JAM', '1876');
INSERT INTO `tomos_countries` VALUES ('je', 'Jersey', 'Bailiwick of Jersey', 'Jersey', 'Bailiwick of Jersey', 'JE', 'JEY', '44');
INSERT INTO `tomos_countries` VALUES ('jo', 'Jordan', 'Hashemite Kingdom of Jordan', 'الأردن', 'المملكة الأردنية الهاشمية', 'JO', 'JOR', '962');
INSERT INTO `tomos_countries` VALUES ('jp', 'Japan', 'Japan', '日本', '日本', 'JP', 'JPN', '81');
INSERT INTO `tomos_countries` VALUES ('kz', 'Kazakhstan', 'Republic of Kazakhstan', 'Қазақстан', 'Қазақстан Республикасы', 'KZ', 'KAZ', '76');
INSERT INTO `tomos_countries` VALUES ('ke', 'Kenya', 'Republic of Kenya', 'Kenya', 'Republic of Kenya', 'KE', 'KEN', '254');
INSERT INTO `tomos_countries` VALUES ('kg', 'Kyrgyzstan', 'Kyrgyz Republic', 'Кыргызстан', 'Кыргыз Республикасы', 'KG', 'KGZ', '996');
INSERT INTO `tomos_countries` VALUES ('kh', 'Cambodia', 'Kingdom of Cambodia', 'Kâmpŭchéa', 'ព្រះរាជាណាចក្រកម្ពុជា', 'KH', 'KHM', '855');
INSERT INTO `tomos_countries` VALUES ('ki', 'Kiribati', 'Independent and Sovereign Republic of Kiribati', 'Kiribati', 'Independent and Sovereign Republic of Kiribati', 'KI', 'KIR', '686');
INSERT INTO `tomos_countries` VALUES ('kn', 'Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevisa', 'Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevisa', 'KN', 'KNA', '1869');
INSERT INTO `tomos_countries` VALUES ('kr', 'South Korea', 'Republic of Korea', '대한민국', '한국', 'KR', 'KOR', '82');
INSERT INTO `tomos_countries` VALUES ('xk', 'Kosovo', 'Republic of Kosovo', 'Kosova', 'Republika e Kosovës', 'XK', 'UNK', '383');
INSERT INTO `tomos_countries` VALUES ('kw', 'Kuwait', 'State of Kuwait', 'الكويت', 'دولة الكويت', 'KW', 'KWT', '965');
INSERT INTO `tomos_countries` VALUES ('la', 'Laos', 'Lao People\'s Democratic Republic', 'ສປປລາວ', 'ສາທາລະນະ ຊາທິປະໄຕ ຄົນລາວ ຂອງ', 'LA', 'LAO', '856');
INSERT INTO `tomos_countries` VALUES ('lb', 'Lebanon', 'Lebanese Republic', 'لبنان', 'الجمهورية اللبنانية', 'LB', 'LBN', '961');
INSERT INTO `tomos_countries` VALUES ('lr', 'Liberia', 'Republic of Liberia', 'Liberia', 'Republic of Liberia', 'LR', 'LBR', '231');
INSERT INTO `tomos_countries` VALUES ('ly', 'Libya', 'State of Libya', '‏ليبيا', 'الدولة ليبيا', 'LY', 'LBY', '218');
INSERT INTO `tomos_countries` VALUES ('lc', 'Saint Lucia', 'Saint Lucia', 'Saint Lucia', 'Saint Lucia', 'LC', 'LCA', '1758');
INSERT INTO `tomos_countries` VALUES ('li', 'Liechtenstein', 'Principality of Liechtenstein', 'Liechtenstein', 'Fürstentum Liechtenstein', 'LI', 'LIE', '423');
INSERT INTO `tomos_countries` VALUES ('lk', 'Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'ශ්‍රී ලංකාව', 'ශ්‍රී ලංකා ප්‍රජාතාන්ත්‍රික සමාජවාදී ජනරජය', 'LK', 'LKA', '94');
INSERT INTO `tomos_countries` VALUES ('ls', 'Lesotho', 'Kingdom of Lesotho', 'Lesotho', 'Kingdom of Lesotho', 'LS', 'LSO', '266');
INSERT INTO `tomos_countries` VALUES ('lt', 'Lithuania', 'Republic of Lithuania', 'Lietuva', 'Lietuvos Respublikos', 'LT', 'LTU', '370');
INSERT INTO `tomos_countries` VALUES ('lu', 'Luxembourg', 'Grand Duchy of Luxembourg', 'Luxemburg', 'Großherzogtum Luxemburg', 'LU', 'LUX', '352');
INSERT INTO `tomos_countries` VALUES ('lv', 'Latvia', 'Republic of Latvia', 'Latvija', 'Latvijas Republikas', 'LV', 'LVA', '371');
INSERT INTO `tomos_countries` VALUES ('mo', 'Macau', 'Macao Special Administrative Region of the People\'s Republic of China', 'Macau', 'Região Administrativa Especial de Macau da República Popular da China', 'MO', 'MAC', '853');
INSERT INTO `tomos_countries` VALUES ('mf', 'Saint Martin', 'Saint Martin', 'Saint-Martin', 'Saint-Martin', 'MF', 'MAF', '590');
INSERT INTO `tomos_countries` VALUES ('ma', 'Morocco', 'Kingdom of Morocco', 'المغرب', 'المملكة المغربية', 'MA', 'MAR', '212');
INSERT INTO `tomos_countries` VALUES ('mc', 'Monaco', 'Principality of Monaco', 'Monaco', 'Principauté de Monaco', 'MC', 'MCO', '377');
INSERT INTO `tomos_countries` VALUES ('md', 'Moldova', 'Republic of Moldova', 'Moldova', 'Republica Moldova', 'MD', 'MDA', '373');
INSERT INTO `tomos_countries` VALUES ('mg', 'Madagascar', 'Republic of Madagascar', 'Madagascar', 'République de Madagascar', 'MG', 'MDG', '261');
INSERT INTO `tomos_countries` VALUES ('mv', 'Maldives', 'Republic of the Maldives', 'ދިވެހިރާއްޖޭގެ', 'ދިވެހިރާއްޖޭގެ ޖުމްހޫރިއްޔާ', 'MV', 'MDV', '960');
INSERT INTO `tomos_countries` VALUES ('mx', 'Mexico', 'United Mexican States', 'México', 'Estados Unidos Mexicanos', 'MX', 'MEX', '52');
INSERT INTO `tomos_countries` VALUES ('mh', 'Marshall Islands', 'Republic of the Marshall Islands', 'Marshall Islands', 'Republic of the Marshall Islands', 'MH', 'MHL', '692');
INSERT INTO `tomos_countries` VALUES ('mk', 'Macedonia', 'Republic of Macedonia', 'Македонија', 'Република Македонија', 'MK', 'MKD', '389');
INSERT INTO `tomos_countries` VALUES ('ml', 'Mali', 'Republic of Mali', 'Mali', 'République du Mali', 'ML', 'MLI', '223');
INSERT INTO `tomos_countries` VALUES ('mt', 'Malta', 'Republic of Malta', 'Malta', 'Republic of Malta', 'MT', 'MLT', '356');
INSERT INTO `tomos_countries` VALUES ('mm', 'Myanmar', 'Republic of the Union of Myanmar', 'မြန်မာ', 'ပြည်ထောင်စု သမ္မတ မြန်မာနိုင်ငံတော်', 'MM', 'MMR', '95');
INSERT INTO `tomos_countries` VALUES ('me', 'Montenegro', 'Montenegro', 'Црна Гора', 'Црна Гора', 'ME', 'MNE', '382');
INSERT INTO `tomos_countries` VALUES ('mn', 'Mongolia', 'Mongolia', 'Монгол улс', 'Монгол улс', 'MN', 'MNG', '976');
INSERT INTO `tomos_countries` VALUES ('mp', 'Northern Mariana Islands', 'Commonwealth of the Northern Mariana Islands', 'Northern Mariana Islands', 'Commonwealth of the Northern Mariana Islands', 'MP', 'MNP', '1670');
INSERT INTO `tomos_countries` VALUES ('mz', 'Mozambique', 'Republic of Mozambique', 'Moçambique', 'República de Moçambique', 'MZ', 'MOZ', '258');
INSERT INTO `tomos_countries` VALUES ('mr', 'Mauritania', 'Islamic Republic of Mauritania', 'موريتانيا', 'الجمهورية الإسلامية الموريتانية', 'MR', 'MRT', '222');
INSERT INTO `tomos_countries` VALUES ('ms', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'MS', 'MSR', '1664');
INSERT INTO `tomos_countries` VALUES ('mq', 'Martinique', 'Martinique', 'Martinique', 'Martinique', 'MQ', 'MTQ', '596');
INSERT INTO `tomos_countries` VALUES ('mu', 'Mauritius', 'Republic of Mauritius', 'Mauritius', 'Republic of Mauritius', 'MU', 'MUS', '230');
INSERT INTO `tomos_countries` VALUES ('mw', 'Malawi', 'Republic of Malawi', 'Malawi', 'Republic of Malawi', 'MW', 'MWI', '265');
INSERT INTO `tomos_countries` VALUES ('my', 'Malaysia', 'Malaysia', 'Malaysia', 'Malaysia', 'MY', 'MYS', '60');
INSERT INTO `tomos_countries` VALUES ('yt', 'Mayotte', 'Department of Mayotte', 'Mayotte', 'Département de Mayotte', 'YT', 'MYT', '262');
INSERT INTO `tomos_countries` VALUES ('na', 'Namibia', 'Republic of Namibia', 'Namibië', 'Republiek van Namibië', 'NA', 'NAM', '264');
INSERT INTO `tomos_countries` VALUES ('nc', 'New Caledonia', 'New Caledonia', 'Nouvelle-Calédonie', 'Nouvelle-Calédonie', 'NC', 'NCL', '687');
INSERT INTO `tomos_countries` VALUES ('ne', 'Niger', 'Republic of Niger', 'Niger', 'République du Niger', 'NE', 'NER', '227');
INSERT INTO `tomos_countries` VALUES ('nf', 'Norfolk Island', 'Territory of Norfolk Island', 'Norfolk Island', 'Territory of Norfolk Island', 'NF', 'NFK', '672');
INSERT INTO `tomos_countries` VALUES ('ng', 'Nigeria', 'Federal Republic of Nigeria', 'Nigeria', 'Federal Republic of Nigeria', 'NG', 'NGA', '234');
INSERT INTO `tomos_countries` VALUES ('ni', 'Nicaragua', 'Republic of Nicaragua', 'Nicaragua', 'República de Nicaragua', 'NI', 'NIC', '505');
INSERT INTO `tomos_countries` VALUES ('nu', 'Niue', 'Niue', 'Niue', 'Niue', 'NU', 'NIU', '683');
INSERT INTO `tomos_countries` VALUES ('nl', 'Netherlands', 'Netherlands', 'Nederland', 'Nederland', 'NL', 'NLD', '31');
INSERT INTO `tomos_countries` VALUES ('no', 'Norway', 'Kingdom of Norway', 'Noreg', 'Kongeriket Noreg', 'NO', 'NOR', '47');
INSERT INTO `tomos_countries` VALUES ('np', 'Nepal', 'Federal Democratic Republic of Nepal', 'नपल', 'नेपाल संघीय लोकतान्त्रिक गणतन्त्र', 'NP', 'NPL', '977');
INSERT INTO `tomos_countries` VALUES ('nr', 'Nauru', 'Republic of Nauru', 'Nauru', 'Republic of Nauru', 'NR', 'NRU', '674');
INSERT INTO `tomos_countries` VALUES ('nz', 'New Zealand', 'New Zealand', 'New Zealand', 'New Zealand', 'NZ', 'NZL', '64');
INSERT INTO `tomos_countries` VALUES ('om', 'Oman', 'Sultanate of Oman', 'عمان', 'سلطنة عمان', 'OM', 'OMN', '968');
INSERT INTO `tomos_countries` VALUES ('pk', 'Pakistan', 'Islamic Republic of Pakistan', 'Pakistan', 'Islamic Republic of Pakistan', 'PK', 'PAK', '92');
INSERT INTO `tomos_countries` VALUES ('pa', 'Panama', 'Republic of Panama', 'Panamá', 'República de Panamá', 'PA', 'PAN', '507');
INSERT INTO `tomos_countries` VALUES ('pn', 'Pitcairn Islands', 'Pitcairn Group of Islands', 'Pitcairn Islands', 'Pitcairn Group of Islands', 'PN', 'PCN', '64');
INSERT INTO `tomos_countries` VALUES ('pe', 'Peru', 'Republic of Peru', 'Piruw', 'Piruw Suyu', 'PE', 'PER', '51');
INSERT INTO `tomos_countries` VALUES ('ph', 'Philippines', 'Republic of the Philippines', 'Philippines', 'Republic of the Philippines', 'PH', 'PHL', '63');
INSERT INTO `tomos_countries` VALUES ('pw', 'Palau', 'Republic of Palau', 'Palau', 'Republic of Palau', 'PW', 'PLW', '680');
INSERT INTO `tomos_countries` VALUES ('pg', 'Papua New Guinea', 'Independent State of Papua New Guinea', 'Papua New Guinea', 'Independent State of Papua New Guinea', 'PG', 'PNG', '675');
INSERT INTO `tomos_countries` VALUES ('pl', 'Poland', 'Republic of Poland', 'Polska', 'Rzeczpospolita Polska', 'PL', 'POL', '48');
INSERT INTO `tomos_countries` VALUES ('pr', 'Puerto Rico', 'Commonwealth of Puerto Rico', 'Puerto Rico', 'Commonwealth of Puerto Rico', 'PR', 'PRI', '1787');
INSERT INTO `tomos_countries` VALUES ('kp', 'North Korea', 'Democratic People\'s Republic of Korea', '북한', '조선 민주주의 인민 공화국', 'KP', 'PRK', '850');
INSERT INTO `tomos_countries` VALUES ('pt', 'Portugal', 'Portuguese Republic', 'Portugal', 'República português', 'PT', 'PRT', '351');
INSERT INTO `tomos_countries` VALUES ('py', 'Paraguay', 'Republic of Paraguay', 'Paraguái', 'Tetã Paraguái', 'PY', 'PRY', '595');
INSERT INTO `tomos_countries` VALUES ('ps', 'Palestine', 'State of Palestine', 'فلسطين', 'دولة فلسطين', 'PS', 'PSE', '970');
INSERT INTO `tomos_countries` VALUES ('pf', 'French Polynesia', 'French Polynesia', 'Polynésie française', 'Polynésie française', 'PF', 'PYF', '689');
INSERT INTO `tomos_countries` VALUES ('qa', 'Qatar', 'State of Qatar', 'قطر', 'دولة قطر', 'QA', 'QAT', '974');
INSERT INTO `tomos_countries` VALUES ('re', 'Réunion', 'Réunion Island', 'La Réunion', 'Ile de la Réunion', 'RE', 'REU', '262');
INSERT INTO `tomos_countries` VALUES ('ro', 'Romania', 'Romania', 'România', 'România', 'RO', 'ROU', '40');
INSERT INTO `tomos_countries` VALUES ('ru', 'Russia', 'Russian Federation', 'Россия', 'Российская Федерация', 'RU', 'RUS', '7');
INSERT INTO `tomos_countries` VALUES ('rw', 'Rwanda', 'Republic of Rwanda', 'Rwanda', 'Republic of Rwanda', 'RW', 'RWA', '250');
INSERT INTO `tomos_countries` VALUES ('sa', 'Saudi Arabia', 'Kingdom of Saudi Arabia', 'العربية السعودية', 'المملكة العربية السعودية', 'SA', 'SAU', '966');
INSERT INTO `tomos_countries` VALUES ('sd', 'Sudan', 'Republic of the Sudan', 'السودان', 'جمهورية السودان', 'SD', 'SDN', '249');
INSERT INTO `tomos_countries` VALUES ('sn', 'Senegal', 'Republic of Senegal', 'Sénégal', 'République du Sénégal', 'SN', 'SEN', '221');
INSERT INTO `tomos_countries` VALUES ('sg', 'Singapore', 'Republic of Singapore', '新加坡', '新加坡共和国', 'SG', 'SGP', '65');
INSERT INTO `tomos_countries` VALUES ('gs', 'South Georgia', 'South Georgia and the South Sandwich Islands', 'South Georgia', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', '500');
INSERT INTO `tomos_countries` VALUES ('sj', 'Svalbard and Jan Mayen', 'Svalbard og Jan Mayen', 'Svalbard og Jan Mayen', 'Svalbard og Jan Mayen', 'SJ', 'SJM', '4779');
INSERT INTO `tomos_countries` VALUES ('sb', 'Solomon Islands', 'Solomon Islands', 'Solomon Islands', 'Solomon Islands', 'SB', 'SLB', '677');
INSERT INTO `tomos_countries` VALUES ('sl', 'Sierra Leone', 'Republic of Sierra Leone', 'Sierra Leone', 'Republic of Sierra Leone', 'SL', 'SLE', '232');
INSERT INTO `tomos_countries` VALUES ('sv', 'El Salvador', 'Republic of El Salvador', 'El Salvador', 'República de El Salvador', 'SV', 'SLV', '503');
INSERT INTO `tomos_countries` VALUES ('sm', 'San Marino', 'Most Serene Republic of San Marino', 'San Marino', 'Serenissima Repubblica di San Marino', 'SM', 'SMR', '378');
INSERT INTO `tomos_countries` VALUES ('so', 'Somalia', 'Federal Republic of Somalia', 'الصومال‎‎', 'جمهورية الصومال‎‎', 'SO', 'SOM', '252');
INSERT INTO `tomos_countries` VALUES ('pm', 'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'Saint-Pierre-et-Miquelon', 'Collectivité territoriale de Saint-Pierre-et-Miquelon', 'PM', 'SPM', '508');
INSERT INTO `tomos_countries` VALUES ('rs', 'Serbia', 'Republic of Serbia', 'Србија', 'Република Србија', 'RS', 'SRB', '381');
INSERT INTO `tomos_countries` VALUES ('ss', 'South Sudan', 'Republic of South Sudan', 'South Sudan', 'Republic of South Sudan', 'SS', 'SSD', '211');
INSERT INTO `tomos_countries` VALUES ('st', 'São Tomé and Príncipe', 'Democratic Republic of São Tomé and Príncipe', 'São Tomé e Príncipe', 'República Democrática do São Tomé e Príncipe', 'ST', 'STP', '239');
INSERT INTO `tomos_countries` VALUES ('sr', 'Suriname', 'Republic of Suriname', 'Suriname', 'Republiek Suriname', 'SR', 'SUR', '597');
INSERT INTO `tomos_countries` VALUES ('sk', 'Slovakia', 'Slovak Republic', 'Slovensko', 'Slovenská republika', 'SK', 'SVK', '421');
INSERT INTO `tomos_countries` VALUES ('si', 'Slovenia', 'Republic of Slovenia', 'Slovenija', 'Republika Slovenija', 'SI', 'SVN', '386');
INSERT INTO `tomos_countries` VALUES ('se', 'Sweden', 'Kingdom of Sweden', 'Sverige', 'Konungariket Sverige', 'SE', 'SWE', '46');
INSERT INTO `tomos_countries` VALUES ('sz', 'Swaziland', 'Kingdom of Swaziland', 'Swaziland', 'Kingdom of Swaziland', 'SZ', 'SWZ', '268');
INSERT INTO `tomos_countries` VALUES ('sx', 'Sint Maarten', 'Sint Maarten', 'Sint Maarten', 'Sint Maarten', 'SX', 'SXM', '1721');
INSERT INTO `tomos_countries` VALUES ('sc', 'Seychelles', 'Republic of Seychelles', 'Sesel', 'Repiblik Sesel', 'SC', 'SYC', '248');
INSERT INTO `tomos_countries` VALUES ('sy', 'Syria', 'Syrian Arab Republic', 'سوريا', 'الجمهورية العربية السورية', 'SY', 'SYR', '963');
INSERT INTO `tomos_countries` VALUES ('tc', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'TC', 'TCA', '1649');
INSERT INTO `tomos_countries` VALUES ('td', 'Chad', 'Republic of Chad', 'تشاد‎', 'جمهورية تشاد', 'TD', 'TCD', '235');
INSERT INTO `tomos_countries` VALUES ('tg', 'Togo', 'Togolese Republic', 'Togo', 'République togolaise', 'TG', 'TGO', '228');
INSERT INTO `tomos_countries` VALUES ('th', 'Thailand', 'Kingdom of Thailand', 'ประเทศไทย', 'ราชอาณาจักรไทย', 'TH', 'THA', '66');
INSERT INTO `tomos_countries` VALUES ('tj', 'Tajikistan', 'Republic of Tajikistan', 'Таджикистан', 'Республика Таджикистан', 'TJ', 'TJK', '992');
INSERT INTO `tomos_countries` VALUES ('tk', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau', 'TK', 'TKL', '690');
INSERT INTO `tomos_countries` VALUES ('tm', 'Turkmenistan', 'Turkmenistan', 'Туркмения', 'Туркменистан', 'TM', 'TKM', '993');
INSERT INTO `tomos_countries` VALUES ('tl', 'Timor-Leste', 'Democratic Republic of Timor-Leste', 'Timor-Leste', 'República Democrática de Timor-Leste', 'TL', 'TLS', '670');
INSERT INTO `tomos_countries` VALUES ('to', 'Tonga', 'Kingdom of Tonga', 'Tonga', 'Kingdom of Tonga', 'TO', 'TON', '676');
INSERT INTO `tomos_countries` VALUES ('tt', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'TT', 'TTO', '1868');
INSERT INTO `tomos_countries` VALUES ('tn', 'Tunisia', 'Tunisian Republic', 'تونس', 'الجمهورية التونسية', 'TN', 'TUN', '216');
INSERT INTO `tomos_countries` VALUES ('tr', 'Turkey', 'Republic of Turkey', 'Türkiye', 'Türkiye Cumhuriyeti', 'TR', 'TUR', '90');
INSERT INTO `tomos_countries` VALUES ('tv', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'TV', 'TUV', '688');
INSERT INTO `tomos_countries` VALUES ('tw', 'Taiwan', 'Republic of China (Taiwan)', '臺灣', '中华民国', 'TW', 'TWN', '886');
INSERT INTO `tomos_countries` VALUES ('tz', 'Tanzania', 'United Republic of Tanzania', 'Tanzania', 'United Republic of Tanzania', 'TZ', 'TZA', '255');
INSERT INTO `tomos_countries` VALUES ('ug', 'Uganda', 'Republic of Uganda', 'Uganda', 'Republic of Uganda', 'UG', 'UGA', '256');
INSERT INTO `tomos_countries` VALUES ('ua', 'Ukraine', 'Ukraine', 'Україна', 'Україна', 'UA', 'UKR', '380');
INSERT INTO `tomos_countries` VALUES ('um', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'UM', 'UMI', null);
INSERT INTO `tomos_countries` VALUES ('uy', 'Uruguay', 'Oriental Republic of Uruguay', 'Uruguay', 'República Oriental del Uruguay', 'UY', 'URY', '598');
INSERT INTO `tomos_countries` VALUES ('us', 'United States', 'United States of America', 'United States', 'United States of America', 'US', 'USA', '1');
INSERT INTO `tomos_countries` VALUES ('uz', 'Uzbekistan', 'Republic of Uzbekistan', 'Узбекистан', 'Республика Узбекистан', 'UZ', 'UZB', '998');
INSERT INTO `tomos_countries` VALUES ('va', 'Vatican City', 'Vatican City State', 'Vaticano', 'Stato della Città del Vaticano', 'VA', 'VAT', '3906698');
INSERT INTO `tomos_countries` VALUES ('vc', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VC', 'VCT', '1784');
INSERT INTO `tomos_countries` VALUES ('ve', 'Venezuela', 'Bolivarian Republic of Venezuela', 'Venezuela', 'República Bolivariana de Venezuela', 'VE', 'VEN', '58');
INSERT INTO `tomos_countries` VALUES ('vg', 'British Virgin Islands', 'Virgin Islands', 'British Virgin Islands', 'Virgin Islands', 'VG', 'VGB', '1284');
INSERT INTO `tomos_countries` VALUES ('vi', 'United States Virgin Islands', 'Virgin Islands of the United States', 'United States Virgin Islands', 'Virgin Islands of the United States', 'VI', 'VIR', '1340');
INSERT INTO `tomos_countries` VALUES ('vn', 'Vietnam', 'Socialist Republic of Vietnam', 'Việt Nam', 'Cộng hòa xã hội chủ nghĩa Việt Nam', 'VN', 'VNM', '84');
INSERT INTO `tomos_countries` VALUES ('vu', 'Vanuatu', 'Republic of Vanuatu', 'Vanuatu', 'Ripablik blong Vanuatu', 'VU', 'VUT', '678');
INSERT INTO `tomos_countries` VALUES ('wf', 'Wallis and Futuna', 'Territory of the Wallis and Futuna Islands', 'Wallis et Futuna', 'Territoire des îles Wallis et Futuna', 'WF', 'WLF', '681');
INSERT INTO `tomos_countries` VALUES ('ws', 'Samoa', 'Independent State of Samoa', 'Samoa', 'Independent State of Samoa', 'WS', 'WSM', '685');
INSERT INTO `tomos_countries` VALUES ('ye', 'Yemen', 'Republic of Yemen', 'اليَمَن', 'الجمهورية اليمنية', 'YE', 'YEM', '967');
INSERT INTO `tomos_countries` VALUES ('za', 'South Africa', 'Republic of South Africa', 'South Africa', 'Republiek van Suid-Afrika', 'ZA', 'ZAF', '27');
INSERT INTO `tomos_countries` VALUES ('zm', 'Zambia', 'Republic of Zambia', 'Zambia', 'Republic of Zambia', 'ZM', 'ZMB', '260');
INSERT INTO `tomos_countries` VALUES ('zw', 'Zimbabwe', 'Republic of Zimbabwe', 'Zimbabwe', 'Republic of Zimbabwe', 'ZW', 'ZWE', '263');
INSERT INTO `tomos_countries` VALUES ('bq', 'Caribbean Netherlands', 'Bonaire, Sint Eustatius and Saba', 'Caribbean Netherlands', 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', '599');
INSERT INTO `tomos_countries` VALUES ('sh', 'Saint Helena', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena', 'Saint Helena', 'SH', 'SHN', '290');
SET FOREIGN_KEY_CHECKS=1;
